### ISSUE TITLE
Understanding the code

### ISSUE THREAD

**Issue by abulhol** [MAECProject/cuckoo#6]
Hi Ivan,
I am trying to learn from maec41.py in your fork, but here is something that does not make sense to me: 
In createActionNet (line 151), you create a dictionary object_properties which is not used at all:
```
if layer7_protocol is not None:
            object_properties = {"xsi:type": "NetworkConnectionObjectType",
                                 "layer4_protocol": {"value": layer4_protocol, "force_datatype": True},
                                 "layer7_protocol": {"value": layer7_protocol, "force_datatype": True}}
etc...
```

I am looking myself for a good way to create actions and objects for HTTP requests, so I think I can learn from your converter.

**Comment by abulhol** [comment]
Hi there,
I just found out myself how the code works - the people who wrote this have definitely done a great job!
The line where the object_properties are attached to the object is this one of course:
```
associated_object = {"id": maec.utils.idgen.create_id(prefix="object"), "properties": object_properties}
```

**Comment by ikiril01** [comment]
Hi @abulhol, that's it! Glad you figured it out :)
